sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: PRk6Gf+yoIhUdPmGOqOBsjIyTPIjmmVxuBh5xl/zXOmsuR462iVFkr4k5xcOBmpVMGdLCSqkmt7/ZYGGkbzyGYiIQ9W9fBQSwyMR6kc74QYGxcEIuoN2m3OVDfGmc3onlhiAIYY7KoBABTk7X1+F7kIcaE0yk7lb1UnuvDG5GGu4GWasD08JhCXNmxWBrDnWSdb2ftcyVC+vQUZnLzA/kZDykjv1ni+I45DgJ390JKk+8n63Ub0UmTLCSo4t23TNu0Oiy/AQKVa+RDIl+bzJaD3CouYUL25BerkEWX7LX9FQsKB391AEomvZo2ATJAJaLRbRcMIoLUnhHtMN3cHcfGWlxcv3xR7Mnta+ljI0jDagyEwwkwGS/1fWeylFtjh66JSPTTJKySwq+liY/MFiJHT9NjAt012IPq+0uq5JNjW4by+y5p1X/4HscCyIYoGNSbY1bNiL5I/UURyy4Sr2phoLHV18eAc5S9qHwV06CB8/Bx6phbpvnvnc+Is3DgWYVRwt5qgVB1S7wYqsRcVKLEamDvFvRn/qfrzYF1AhOeEiEH4aeocXOWDGE0vf6j2YucU7Ceo/cuqYD2oVGn9lP+6JaIElu630LSPaarZ/tiIlBH//qZOua9FRHzNQO1kYlw9rgkuNX1Ssv9cYssPCHj4vK9uhZ+vrvJyLW8XhriQ=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Tragic-Comedians-A-Study-in-a-Well-known-Story-Volume-3_4463
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy